apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
    creationTimestamp: "2025-06-15T16:26:31Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: projected
    name: direct-pv-projected-volume-0
    namespace: default
    resourceVersion: "3155379"
    uid: 6ddb39ae-d7c6-47d3-8350-ebce4266b5eb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
    storageClassName: nfs-client
    volumeMode: Filesystem
    volumeName: pvc-6ddb39ae-d7c6-47d3-8350-ebce4266b5eb
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 100Mi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
    creationTimestamp: "2025-01-31T04:33:00Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: mongodb-pod
    name: mongodb-volume-mongodb-0
    namespace: default
    resourceVersion: "11983"
    uid: 4905a980-550f-47c5-b03e-344f4a9c0e8b
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
    storageClassName: nfs-client
    volumeMode: Filesystem
    volumeName: pvc-4905a980-550f-47c5-b03e-344f4a9c0e8b
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 100Mi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
    creationTimestamp: "2025-01-31T04:33:08Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: mongodb-pod
    name: mongodb-volume-mongodb-1
    namespace: default
    resourceVersion: "12036"
    uid: 6a8e0297-2085-4717-937f-820075e035be
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
    storageClassName: nfs-client
    volumeMode: Filesystem
    volumeName: pvc-6a8e0297-2085-4717-937f-820075e035be
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 100Mi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
    creationTimestamp: "2025-02-14T08:59:29Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: mysql-pod
    name: mysql-volume-mysql-0
    namespace: default
    resourceVersion: "229446"
    uid: 806d8fe9-259c-41c5-9b0b-3d75e500d5ba
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: nfs-client
    volumeMode: Filesystem
    volumeName: pvc-806d8fe9-259c-41c5-9b0b-3d75e500d5ba
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
    creationTimestamp: "2025-02-14T08:59:35Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: mysql-pod
    name: mysql-volume-mysql-1
    namespace: default
    resourceVersion: "229495"
    uid: ea06c72f-206d-4811-b241-8e61906fb10b
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: nfs-client
    volumeMode: Filesystem
    volumeName: pvc-ea06c72f-206d-4811-b241-8e61906fb10b
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
