apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-lb-service
spec:
  type: LoadBalancer
  ports:
    - name: "27017"
      port: 27017
      nodePort: 32029
      targetPort: 27017
  selector:
    app: mongodb-pod
